
RapidFall.Config = {
	
	MOVE_LEFT : RapidFall.Constants.KeyCodes.LEFT_ARROW,
	MOVE_RIGHT : RapidFall.Constants.KeyCodes.RIGHT_ARROW,
	PHYSICS_FRAME_TIME : 5,
	GRAVITY : -0.0001,
	
	FIELD_HALF_WIDTH : 45,
	FIELD_HALF_HEIGHT : 35,
	
	PLAYER_RUNNING_SPEED : 0.2,
	
	PLATFORM_SPEED : 0.10,
	PLATFORM_SPAWN_INTERVAL : 500,
	PLATFORM_HALF_WIDTH : 10,
	PLATFORM_HALF_HEIGHT : 1,
	PLATFORM_X_VARIANCE : 50,
	
};