
RapidFall.Config = {
	
	MOVE_LEFT : RapidFall.Constants.KeyCodes.LEFT_ARROW,
	MOVE_RIGHT : RapidFall.Constants.KeyCodes.RIGHT_ARROW,
	PHYSICS_FRAME_TIME : 5,
	GRAVITY : -9.81,
	
	FIELD_HALF_WIDTH : 45,
	FIELD_HALF_HEIGHT : 35,
	
	PLAYER_RUNNING_ACCELERATION : 0.1,
	PLAYER_MAX_SPEED : 0.1,
	PLAYER_WEIGHT : 70,
	
	PLATFORM_SPEED : 0.05,
	PLATFORM_SPAWN_INTERVAL : 1500,
	PLATFORM_HALF_WIDTH : 10,
	PLATFORM_HALF_HEIGHT : 0.5,
	PLATFORM_X_VARIANCE : 50,
	
};